packages:
  - 'packages/*'
  - 'example/*'
catalogs:
  electron30:
    electron: ^33.0.0
    electron-builder: ^25.1.8
  ts:
    typescript: ^5.0.2
    ts-node: ^10.9.2
    tslib: ^2.8.0
    "@types/node": ^22.7.7
